###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "cuizk",
  "password": "123"
}

###
GET http://localhost:8080/logout

###
GET http://localhost:8080/auth/refresh_token

###
GET http://localhost:8080/auth/hello
